import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#351000",
        "on-tertiary-fixed-variant": "#7b2f00",
        "tertiary-fixed-dim": "#ffb694",
        "primary-fixed": "#d7e2ff",
        "surface-container-highest": "#e1e3e4",
        "error-container": "#ffdad6",
        "secondary-fixed": "#dbe4ed",
        "on-primary-fixed": "#001a40",
        "surface-dim": "#d9dadb",
        "primary": "#003f87",
        "surface-container": "#edeeef",
        "inverse-surface": "#2e3132",
        "on-secondary-container": "#5b646b",
        "primary-fixed-dim": "#acc7ff",
        "surface-bright": "#f8f9fa",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "tertiary-fixed": "#ffdbcc",
        "primary-container": "#0056b3",
        "on-primary-container": "#bbd0ff",
        "on-surface": "#191c1d",
        "background": "#f8f9fa",
        "inverse-primary": "#acc7ff",
        "secondary-container": "#d8e1ea",
        "surface": "#f8f9fa",
        "on-secondary-fixed-variant": "#3f484f",
        "surface-container-low": "#f3f4f5",
        "on-secondary-fixed": "#141d23",
        "surface-tint": "#115cb9",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#bfc8d0",
        "outline-variant": "#c2c6d4",
        "on-tertiary-container": "#ffc2a7",
        "tertiary": "#722b00",
        "on-background": "#191c1d",
        "surface-variant": "#e1e3e4",
        "tertiary-container": "#983c00",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#424752",
        "surface-container-high": "#e7e8e9",
        "outline": "#727784",
        "secondary": "#575f67",
        "on-primary-fixed-variant": "#004491",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        gutter: "24px",
        "container-max": "1440px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "data-mono": ["Geist", "monospace"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["clamp(1.75rem, 5vw, 32px)", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-mono": ["clamp(12px, 2vw, 14px)", { lineHeight: "1.4", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-sm": ["clamp(12px, 2vw, 14px)", { lineHeight: "1.4", fontWeight: "400" }],
        "headline-md": ["clamp(1.125rem, 3vw, 20px)", { lineHeight: "1.4", fontWeight: "600" }],
        "display-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["clamp(14px, 2vw, 16px)", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
